main: uk.co.harieo.eggs.Eggs
version: 1.0.0
name: Eggs
author: Harieo
api-version: '1.15'
depend:
    - MinigamesCore

commands:
    force:
        description: 'Forces the game to start'
        permission: 'quacktopia.minigames.force'
    maps:
        description: 'Formats a game map'
        permission: 'quacktopia.minigames.map'
        aliases:
            - map
    team:
        description: 'Allows you to join a team with /team'

permissions:
    quacktopia.minigames.*:
        description: 'Allows use of all minigame admin commands'
        default: op
        children:
            - quacktopia.minigames.force
            - quacktopia.minigames.map
    quacktopia.minigames.force:
        description: 'Allows the use of /force'
        default: op
    quacktopia.minigames.map:
        description: 'Allows the use of /maps for map formatting'
        default: op