main: uk.co.harieo.eggs.Eggs
version: 1.0.0
name: Eggs
author: Harieo
api-version: '1.15'
depend:
    - MinigamesCore

commands:
    force:
        description: 'Forces the game to start'
        permission: 'quacktopia.minigames.force'
    maps:
        description: 'Formats a game map'
        permission: 'quacktopia.minigames.map'
        aliases:
            - map
    team:
        description: 'Allows you to join a team with /team'
    shop:
        description: 'Allows you to use the power-up shop'
    coins:
        description: 'Allows you to give coins to players with /coins'
        permission: 'quacktopia.eggs.coins'

permissions:
    quacktopia.minigames.*:
        description: 'Allows use of all minigame admin commands'
        default: op
        children:
            - quacktopia.minigames.force
            - quacktopia.minigames.map
    quacktopia.minigames.force:
        description: 'Allows the use of /force'
        default: op
    quacktopia.minigames.map:
        description: 'Allows the use of /maps for map formatting'
        default: op
    quacktopia.minigames.spectate:
        description: 'Allows you to join a game while it is in progress'
        default: op
    quacktopia.eggs.coins:
        description: 'Allows the use of /coins'
        default: op